---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: VAR_NAME
  name: VAR_NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      run: VAR_NAME
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: VAR_NAME
    spec:
      containers:
      - image: VAR_IMAGE
        name: VAR_NAME
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /alive
            port: 5000
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 5000
          initialDelaySeconds: 3
          timeoutSeconds: 3
        resources: {}
status: {}
