---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: VAR_NAME
  name: VAR_NAME
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    run: VAR_NAME
  type: NodePort
status:
  loadBalancer: {}
