---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: app
  namespace: default
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:0.0.*
spec:
  releaseName: myapp
  chart:
    git: ssh://git@github.com/BillMills/flux-gitops
    ref: flux
    path: app-chart
    name: app-chart
